#!/usr/bin/env python3
"""
Generate enhanced CSV with summaries and key takeaways.
Claude will provide the summaries for each article.
"""

import json
import csv

def extract_excerpt(text: str, target_length: int = 175) -> str:
    """Extract first 150-200 characters as excerpt."""
    if not text:
        return ""

    text = text.strip()
    if len(text) <= target_length:
        return text

    excerpt = text[:target_length]
    last_period = max(excerpt.rfind('.'), excerpt.rfind('!'), excerpt.rfind('?'))

    if last_period > 100:
        excerpt = excerpt[:last_period + 1]
    else:
        excerpt = excerpt[:target_length].rsplit(' ', 1)[0] + '...'

    return excerpt.strip()


# Article summaries and key takeaways (generated by Claude)
ARTICLE_METADATA = {}  # Will be populated

def main():
    # Load original CSV
    with open('techtiff_articles.csv', 'r') as f:
        reader = csv.DictReader(f)
        csv_data = list(reader)

    # Load article content
    with open('techtiff_articles_content.json', 'r') as f:
        content_data = json.load(f)

    # Create lookup by URL
    content_by_url = {item['url']: item for item in content_data}

    # Build enhanced rows
    enhanced_rows = []

    for row in csv_data:
        url = row['url']
        content = content_by_url.get(url, {})

        # Get content text
        body = content.get('body', '')
        word_count = content.get('word_count', 0)
        reading_time = content.get('reading_time', 0)

        # Extract excerpt from body
        excerpt = extract_excerpt(body)

        # Get metadata (to be filled in by Claude)
        metadata = ARTICLE_METADATA.get(url, {
            'summary': '',
            'key_takeaways': ''
        })

        enhanced_row = {
            **row,
            'summary': metadata['summary'],
            'key_takeaways': metadata['key_takeaways'],
            'word_count': str(word_count),
            'reading_time': str(reading_time),
            'excerpt': excerpt
        }

        enhanced_rows.append(enhanced_row)

    # Save enhanced CSV
    fieldnames = [
        'title', 'url', 'slug', 'published_at', 'subtitle', 'thumbnail_url',
        'content_type', 'keywords', 'summary', 'key_takeaways',
        'word_count', 'reading_time', 'excerpt'
    ]

    with open('techtiff_articles_enhanced.csv', 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(enhanced_rows)

    print(f"✅ Generated enhanced CSV with {len(enhanced_rows)} articles")
    print(f"   Output: techtiff_articles_enhanced.csv")


if __name__ == "__main__":
    main()
